# SPDX-FileCopyrightText: Copyright (C) 2021-2026 Software Radio Systems Limited
# SPDX-License-Identifier: BSD-3-Clause-Open-MPI

spec:
  inputs:
    ocudu_path:
      type: string
      default: ocudu/ocudu
      description: "OCUDU repository path."
    ocudu_ref:
      type: string
      default: dev
      description: "OCUDU reference branch or tag."
---
include:
  - project: $[[ inputs.ocudu_path ]]
    ref: $[[ inputs.ocudu_ref ]]
    file: .gitlab/ci-shared/workflow.yml
  - project: $[[ inputs.ocudu_path ]]
    ref: $[[ inputs.ocudu_ref ]]
    file: .gitlab/ci-shared/static.yml
  - project: $[[ inputs.ocudu_path ]]
    ref: $[[ inputs.ocudu_ref ]]
    file: .gitlab/ci-shared/gitlab_settings/.gitlab-ci.yml
    inputs:
      ocudu_path: $[[ inputs.ocudu_path ]]
      ocudu_ref: $[[ inputs.ocudu_ref ]]

variables:
  OCUDU_REGISTRY_URI: ${CI_TEMPLATE_REGISTRY_HOST}/$[[ inputs.ocudu_path ]]

stages:
  - ci
  - static
  - child
  - publish

headers:
  stage: ci
  extends: .headers

################################################################################
## Images
################################################################################

linuxptp image:
  stage: child
  variables:
    LINUXPTP_VERSION: "v4.4"
    CT_VERSION: "2.0.0"
  rules:
    - if: $ON_MR
      changes:
        paths:
          - images/linuxptp/**/*
    - if: $ON_DEFAULT_BRANCH
      changes:
        paths:
          - images/linuxptp/**/*
  trigger:
    strategy: mirror
    include:
      - local: images/linuxptp/.gitlab-ci.yml
        inputs:
          ocudu_path: $[[ inputs.ocudu_path ]]
          ocudu_ref: $[[ inputs.ocudu_ref ]]
  needs: []

rt-tests image:
  stage: child
  variables:
    RT_TESTS_VERSION: "v2.8"
  rules:
    - if: $ON_MR
      changes:
        paths:
          - images/rt-tests/**/*
    - if: $ON_DEFAULT_BRANCH
      changes:
        paths:
          - images/rt-tests/**/*
  trigger:
    strategy: mirror
    include:
      - local: images/rt-tests/.gitlab-ci.yml
        inputs:
          ocudu_path: $[[ inputs.ocudu_path ]]
          ocudu_ref: $[[ inputs.ocudu_ref ]]
  needs: []

tuned image:
  stage: child
  variables:
    TUNED_VERSION: "v2.21.0"
    CT_VERSION: "1.0.0"
  rules:
    - if: $ON_MR
      changes:
        paths:
          - images/tuned/**/*
    - if: $ON_DEFAULT_BRANCH
      changes:
        paths:
          - images/tuned/**/*
  trigger:
    strategy: mirror
    include:
      - local: images/tuned/.gitlab-ci.yml
        inputs:
          ocudu_path: $[[ inputs.ocudu_path ]]
          ocudu_ref: $[[ inputs.ocudu_ref ]]
  needs: []

################################################################################
## Charts
################################################################################

grafana-ocudu chart:
  stage: child
  rules:
    - changes:
        paths:
          - .gitlab/ci/helm_utils.yml
          - charts/grafana-ocudu/**/*
  trigger:
    strategy: mirror
    include: charts/grafana-ocudu/.gitlab-ci.yml
  needs: []

rt-tests chart:
  stage: child
  rules:
    - changes:
        paths:
          - .gitlab/ci/helm_utils.yml
          - charts/rt-tests/**/*
  trigger:
    strategy: mirror
    include: charts/rt-tests/.gitlab-ci.yml
  needs: []

linuxptp chart:
  stage: child
  rules:
    - changes:
        paths:
          - .gitlab/ci/helm_utils.yml
          - charts/linuxptp/**/*
  trigger:
    strategy: mirror
    include: charts/linuxptp/.gitlab-ci.yml
  needs: []

ru_emulator chart:
  stage: child
  rules:
    - changes:
        paths:
          - .gitlab/ci/helm_utils.yml
          - charts/ru_emulator/**/*
  trigger:
    strategy: mirror
    include: charts/ru_emulator/.gitlab-ci.yml
  needs: []

ocudu-gnb chart:
  stage: child
  rules:
    - changes:
        paths:
          - .gitlab/ci/helm_utils.yml
          - charts/ocudu-gnb/**/*
  trigger:
    strategy: mirror
    include: charts/ocudu-gnb/.gitlab-ci.yml
  needs: []

ocudu-cu chart:
  stage: child
  rules:
    - changes:
        paths:
          - .gitlab/ci/helm_utils.yml
          - charts/ocudu-cu/**/*
  trigger:
    strategy: mirror
    include: charts/ocudu-cu/.gitlab-ci.yml
  needs: []

ocudu-du chart:
  stage: child
  rules:
    - changes:
        paths:
          - .gitlab/ci/helm_utils.yml
          - charts/ocudu-du/**/*
  trigger:
    strategy: mirror
    include: charts/ocudu-du/.gitlab-ci.yml
  needs: []

influxdb3 chart:
  stage: child
  rules:
    - changes:
        paths:
          - .gitlab/ci/helm_utils.yml
          - charts/influxdb3/**/*
  trigger:
    strategy: mirror
    include: charts/influxdb3/.gitlab-ci.yml
  needs: []

tuned chart:
  stage: child
  rules:
    - changes:
        paths:
          - .gitlab/ci/helm_utils.yml
          - charts/tuned/**/*
  trigger:
    strategy: mirror
    include: charts/tuned/.gitlab-ci.yml
  needs: []

onap-smo-lite chart:
  stage: child
  rules:
    - changes:
        paths:
          - .gitlab/ci/helm_utils.yml
          - charts/onap-smo-lite/**/*
  trigger:
    strategy: mirror
    include: charts/onap-smo-lite/.gitlab-ci.yml
  needs: []
