{{- if and .Values.persistence.enabled (eq .Values.persistence.type "pvc") }}

# SPDX-FileCopyrightText: Copyright (C) 2021-2026 Software Radio Systems Limited
# SPDX-License-Identifier: BSD-3-Clause-Open-MPI

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "influxdb3.fullname" . }}-data
  labels:
    app: influxdb3
    component: storage
spec:
  accessModes:
    - {{ .Values.persistence.pvc.accessMode }}
  {{- if .Values.persistence.pvc.storageClassName }}
  storageClassName: {{ .Values.persistence.pvc.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.pvc.size }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "influxdb3.fullname" . }}-plugins
  labels:
    app: influxdb3
    component: storage
spec:
  accessModes:
    - {{ .Values.persistence.pvc.accessMode }}
  {{- if .Values.persistence.pvc.storageClassName }}
  storageClassName: {{ .Values.persistence.pvc.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.pvc.pluginsSize }}
{{- end }}
