{{- if and .Values.service.enabled (eq .Values.service.type "LoadBalancer") }}
#
# Copyright 2021-2025 Software Radio Systems Limited
#
# By using this file, you agree to the terms and conditions set
# forth in the LICENSE file which can be found at the top level of
# the distribution.
#

apiVersion: v1
kind: Service
metadata:
  name: {{ include "srsran-cudu.fullname" . }}-lb
  labels:
    {{- include "srsran-cudu.labels" . | nindent 4 }}
    app.kubernetes.io/component: n2-n3
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  {{- if .Values.service.loadBalancerClass }}
  loadBalancerClass: {{ .Values.service.loadBalancerClass }}
  {{- end }}
  {{- with .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ . }}
  {{- end }}
  {{- with .Values.service.sessionAffinity }}
  sessionAffinity: {{ . }}
  {{- end }}
  ports:
    {{- if .Values.service.ports.n2.enabled }}
    - name: n2
      port: {{ .Values.service.ports.n2.port }}
      targetPort: {{ .Values.service.ports.n2.targetPort | default .Values.service.ports.n2.port }}
      protocol: {{ .Values.service.ports.n2.protocol }}
      {{- if .Values.service.ports.n2.nodePort }}
      nodePort: {{ .Values.service.ports.n2.nodePort }}
      {{- end }}
    {{- end }}
    {{- if .Values.service.ports.n3.enabled }}
    - name: n3
      port: {{ .Values.service.ports.n3.port }}
      targetPort: {{ .Values.service.ports.n3.targetPort | default .Values.service.ports.n3.port }}
      protocol: {{ .Values.service.ports.n3.protocol }}
      {{- if .Values.service.ports.n3.nodePort }}
      nodePort: {{ .Values.service.ports.n3.nodePort }}
      {{- end }}
    {{- end }}
  selector:
    {{- include "srsran-cudu.selectorLabels" . | nindent 4 }}
{{- end }}
