# SPDX-FileCopyrightText: Copyright (C) 2021-2026 Software Radio Systems Limited
# SPDX-License-Identifier: BSD-3-Clause-Open-MPI

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rt-tests.configmapName" . }}
data:
  {{- .Values.config | toYaml | nindent 2 }}

