{{- if .Values.kafka.enabled }}

# SPDX-FileCopyrightText: Copyright (C) 2021-2026 Software Radio Systems Limited
# SPDX-License-Identifier: BSD-3-Clause-Open-MPI

apiVersion: v1
kind: Service
metadata:
  name: {{ include "onap-smo-lite.componentName" (dict "root" . "component" "kafka") }}
  labels:
    {{- include "onap-smo-lite.labels" . | nindent 4 }}
    app.kubernetes.io/component: kafka
spec:
  type: {{ .Values.kafka.service.type }}
  selector:
    {{- include "onap-smo-lite.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: kafka
  ports:
    - name: broker
      port: {{ .Values.kafka.service.port }}
      targetPort: broker
      protocol: TCP
{{- end }}
