{{- if and .Values.kafka.enabled .Values.kafka.auth.enabled }}

# SPDX-FileCopyrightText: Copyright (C) 2021-2026 Software Radio Systems Limited
# SPDX-License-Identifier: BSD-3-Clause-Open-MPI

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "onap-smo-lite.componentName" (dict "root" . "component" "kafka-jaas") }}
  labels:
    {{- include "onap-smo-lite.labels" . | nindent 4 }}
data:
  zk_server_jaas.conf: |-
    Server {
       org.apache.zookeeper.server.auth.DigestLoginModule required
       user_{{ .Values.kafka.auth.username }}={{ .Values.kafka.auth.password }};
    };
  zk_client_jaas.conf: |-
    Client {
       org.apache.zookeeper.server.auth.DigestLoginModule required
       username="{{ .Values.kafka.auth.username }}"
       password="{{ .Values.kafka.auth.password }}";
    };
{{- end }}
