{{- if and .Values.sdnrdb.persistence.enabled (not .Values.sdnrdb.persistence.existingClaim) }}

# SPDX-FileCopyrightText: Copyright (C) 2021-2026 Software Radio Systems Limited
# SPDX-License-Identifier: BSD-3-Clause-Open-MPI
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "onap-smo-lite.fullname" . }}-sdnrdb
  labels:
    {{- include "onap-smo-lite.labels" . | nindent 4 }}
    app.kubernetes.io/component: sdnrdb
spec:
  accessModes:
    {{- toYaml .Values.sdnrdb.persistence.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.sdnrdb.persistence.size }}
  {{- if .Values.sdnrdb.persistence.storageClass }}
  storageClassName: {{ .Values.sdnrdb.persistence.storageClass }}
  {{- end }}
{{- end }}
