# SPDX-FileCopyrightText: Copyright (C) 2021-2026 Software Radio Systems Limited
# SPDX-License-Identifier: BSD-3-Clause-Open-MPI

apiVersion: v1
kind: Service
metadata:
  name: {{ include "onap-smo-lite.fullname" . }}-sdnrdb
  labels:
    {{- include "onap-smo-lite.labels" . | nindent 4 }}
    app.kubernetes.io/component: sdnrdb
spec:
  type: {{ .Values.sdnrdb.service.type }}
  ports:
    - name: http
      port: {{ .Values.sdnrdb.service.port }}
      targetPort: http
  selector:
    {{- include "onap-smo-lite.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: sdnrdb
