{{- if not .Values.sdnr.adminCredentials.existingSecret }}

# SPDX-FileCopyrightText: Copyright (C) 2021-2026 Software Radio Systems Limited
# SPDX-License-Identifier: BSD-3-Clause-Open-MPI
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "onap-smo-lite.fullname" . }}-sdnr-admin
  labels:
    {{- include "onap-smo-lite.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.sdnr.adminCredentials.username | b64enc }}
  password: {{ .Values.sdnr.adminCredentials.password | b64enc }}
{{- end }}
