# SPDX-FileCopyrightText: Copyright (C) 2021-2026 Software Radio Systems Limited
# SPDX-License-Identifier: BSD-3-Clause-Open-MPI

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "onap-smo-lite.fullname" . }}-sdnr-config
  labels:
    {{- include "onap-smo-lite.labels" . | nindent 4 }}
data:
  devicemanager.properties: |-
    {{- with .Values.sdnr.config.devicemanager }}
    {{- tpl . $ | nindent 4 }}
    {{- end }}
  mountpoint-registrar.properties: |-
    {{- with .Values.sdnrRegistrar.config }}
    {{- tpl . $ | nindent 4 }}
    {{- end }}
