{{- if .Values.vesCollector.enabled }}

# SPDX-FileCopyrightText: Copyright (C) 2021-2026 Software Radio Systems Limited
# SPDX-License-Identifier: BSD-3-Clause-Open-MPI

apiVersion: v1
kind: Service
metadata:
  name: {{ include "onap-smo-lite.componentName" (dict "root" . "component" "ves-collector") }}
  labels:
    {{- include "onap-smo-lite.labels" . | nindent 4 }}
    app.kubernetes.io/component: ves-collector
spec:
  type: {{ .Values.vesCollector.service.type }}
  selector:
    {{- include "onap-smo-lite.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: ves-collector
  ports:
    - name: https
      port: {{ .Values.vesCollector.service.port }}
      targetPort: https
      protocol: TCP
{{- end }}
