{{- if .Values.zookeeper.enabled }}

# SPDX-FileCopyrightText: Copyright (C) 2021-2026 Software Radio Systems Limited
# SPDX-License-Identifier: BSD-3-Clause-Open-MPI

apiVersion: v1
kind: Service
metadata:
  name: {{ include "onap-smo-lite.componentName" (dict "root" . "component" "zookeeper") }}
  labels:
    {{- include "onap-smo-lite.labels" . | nindent 4 }}
    app.kubernetes.io/component: zookeeper
spec:
  type: {{ .Values.zookeeper.service.type }}
  selector:
    {{- include "onap-smo-lite.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: zookeeper
  ports:
    - name: client
      port: {{ .Values.zookeeper.service.port }}
      targetPort: client
      protocol: TCP
{{- end }}
