{{- if .Values.service.enabled }}

# SPDX-FileCopyrightText: Copyright (C) 2021-2026 Software Radio Systems Limited
# SPDX-License-Identifier: BSD-3-Clause-Open-MPI

apiVersion: v1
kind: Service
metadata:
  name: {{ include "ocudu-cu.fullname" . }}-lb
  labels:
    {{- include "ocudu-cu.labels" . | nindent 4 }}
    app.kubernetes.io/component: n2n3
spec:
  type: {{ .Values.service.type | default "LoadBalancer" }}
  {{- if eq (.Values.service.type | default "LoadBalancer") "LoadBalancer" }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  {{- if .Values.service.loadBalancerClass }}
  loadBalancerClass: {{ .Values.service.loadBalancerClass }}
  {{- end }}
  {{- with .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ . }}
  {{- end }}
  {{- end }}
  {{- with .Values.service.sessionAffinity }}
  sessionAffinity: {{ . }}
  {{- end }}
  ports:
    {{- if .Values.service.ports.n2.enabled }}
    - name: n2
      port: {{ .Values.service.ports.n2.port }}
      targetPort: {{ .Values.service.ports.n2.targetPort | default .Values.service.ports.n2.port }}
      protocol: {{ .Values.service.ports.n2.protocol }}
      {{- if .Values.service.ports.n2.nodePort }}
      nodePort: {{ .Values.service.ports.n2.nodePort }}
      {{- end }}
    {{- end }}
    {{- if .Values.service.ports.n3.enabled }}
    - name: n3
      port: {{ .Values.service.ports.n3.port }}
      targetPort: {{ .Values.service.ports.n3.targetPort | default .Values.service.ports.n3.port }}
      protocol: {{ .Values.service.ports.n3.protocol }}
      {{- if .Values.service.ports.n3.nodePort }}
      nodePort: {{ .Values.service.ports.n3.nodePort }}
      {{- end }}
    {{- end }}
  selector:
    {{- include "ocudu-cu.selectorLabels" . | nindent 4 }}
{{- end }}
