# SPDX-FileCopyrightText: Copyright (C) 2021-2026 Software Radio Systems Limited
# SPDX-License-Identifier: BSD-3-Clause-Open-MPI

spec:
  inputs:
    ocudu_path:
      type: string
      default: ocudu/ocudu
      description: "OCUDU repository path."
    ocudu_ref:
      type: string
      default: dev
      description: "OCUDU reference branch or tag."
---
include:
  - project: $[[ inputs.ocudu_path ]]
    ref: $[[ inputs.ocudu_ref ]]
    file: .gitlab/ci-shared/docker.yml

stages:
  - test
  - publish
  - manifest

.docker-builder-linuxptp:
  extends: .docker-builder
  variables:
    CONTEXT: images/linuxptp
    VERSION: "${LINUXPTP_VERSION}_${CT_VERSION}"
    BUILD_ARGS: "LINUXPTP_VERSION=${LINUXPTP_VERSION}"
    NAME: linuxptp
    MULTI_ARCH_BUILD: "true"
    REGISTRY_URI: ${CI_REGISTRY}/${CI_PROJECT_PATH}
    REGISTRY_ORG: ""
  parallel:
    matrix:
      - PLATFORM: ["arm64", "amd64"]

only-build-linuxptp:
  stage: test
  extends: .docker-builder-linuxptp
  rules:
    - if: $ON_MR
  variables:
    MODE: test

build-and-publish-linuxptp:
  stage: publish
  extends: .docker-builder-linuxptp
  rules:
    - if: $ON_DEFAULT_BRANCH
    - if: $ON_MR
      when: manual
      allow_failure: true
  variables:
    MODE: publish

docker manifest linuxptp:
  extends: .docker manifest
  stage: manifest
  variables:
    REGISTRY_URI: ${CI_REGISTRY}/${CI_PROJECT_PATH}
    REGISTRY_ORG: ""
    NAME: linuxptp
    VERSION: "${LINUXPTP_VERSION}_${CT_VERSION}"
  needs:
    - job: build-and-publish-linuxptp
      optional: false
