# SPDX-FileCopyrightText: Copyright (C) 2021-2026 Software Radio Systems Limited
# SPDX-License-Identifier: BSD-3-Clause-Open-MPI

include:
  - local: .gitlab/ci/helm_utils.yml

stages:
  - static
  - publish

helm lint:
  extends: .helm lint
  allow_failure: true
  variables:
    CHART_PATH: charts/grafana-ocudu
  before_script:
    - helm repo add influxdata https://helm.influxdata.com

helm version check:
  extends: .helm version check
  variables:
    CHART_PATH: charts/grafana-ocudu
    CHART_NAME: grafana-ocudu

helm publish-dev:
  extends: .helm publish-dev
  variables:
    CHART_PATH: charts/grafana-ocudu
    CHART_NAME: grafana-ocudu
  needs:
    - job: helm lint
    - job: helm version check

helm publish-prod:
  extends: .helm publish-prod
  variables:
    CHART_PATH: charts/grafana-ocudu
    CHART_NAME: grafana-ocudu
