# SPDX-FileCopyrightText: Copyright (C) 2021-2026 Software Radio Systems Limited
# SPDX-License-Identifier: BSD-3-Clause-Open-MPI

apiVersion: v2
name: grafana-ocudu
description: Monitoring stack with Grafana, Telegraf, and InfluxDB3 for OCUDU metrics visualization
kubeVersion: ">= 1.24.0-0"
icon: https://grafana.com/static/img/menu/grafana2.svg
home: https://gitlab.com/ocudu/ocudu_elements/ocudu_helm
sources:
- https://gitlab.com/ocudu/ocudu_elements/ocudu_helm
keywords:
- grafana
- telegraf
- influxdb
- monitoring
- metrics
- observability
- visualization
- ocudu
annotations:
  artifacthub.io/category: monitoring-logging
  artifacthub.io/license: BSD-3-Clause-Open-MPI
  artifacthub.io/operator: "false"
  artifacthub.io/prerelease: "true"
type: application
version: 2.3.2
appVersion: "9.2.10"

dependencies:
  - name: grafana
    repository: "https://grafana.github.io/helm-charts"
    version: "9.2.10"
    alias: grafana
  - name: influxdb3
    repository: "oci://registry.gitlab.com/ocudu/ocudu_elements/ocudu_helm"
    version: "2.2.0"
    alias: influxdb3
