#
# Copyright 2021-2026 Software Radio Systems Limited
#
# By using this file, you agree to the terms and conditions set
# forth in the LICENSE file which can be found at the top level of
# the distribution.
#

apiVersion: v2
name: linuxptp
description: LinuxPTP (PTP4l/PHC2SYS/TS2PHC) for IEEE 1588 precise time synchronization (PoC/Demo)
kubeVersion: ">= 1.24.0-0"
icon: https://linuxptp.nwtime.org/images/logo.png
home: https://gitlab.com/ocudu/ocudu_elements/ocudu_helm
sources:
- https://gitlab.com/ocudu/ocudu_elements/ocudu_helm
- https://github.com/richardcochran/linuxptp
keywords:
- linuxptp
- ptp4l
- phc2sys
- ptp
- timing
- synchronization
- telecom
- ocudu
annotations:
  artifacthub.io/category: synchronization
  artifacthub.io/license: MIT
  artifacthub.io/operator: "false"
  artifacthub.io/prerelease: "true"
type: application
version: 2.0.0
appVersion: "4.4.0"
