#
# Copyright 2021-2026 Software Radio Systems Limited
#
# By using this file, you agree to the terms and conditions set
# forth in the LICENSE file which can be found at the top level of
# the distribution.
#

apiVersion: v2
name: ru-emulator
description: OCUDU Radio Unit (O-RU) emulator for testing gNB deployments with OpenFronthaul interface
kubeVersion: ">= 1.24.0-0"
icon: https://gitlab.com/ocudu/ocudu_elements/ocudu_helm/-/raw/main/docs/logo.png
home: https://gitlab.com/ocudu/ocudu_elements/ocudu_helm
sources:
- https://gitlab.com/ocudu/ocudu_elements/ocudu_helm
- https://gitlab.com/ocudu/ocudu
keywords:
- ocudu
- ru
- oru
- radio-unit
- emulator
- openfronthaul
- 5g
- testing
- ran
annotations:
  artifacthub.io/category: openfronthaul
  artifacthub.io/license: MIT
  artifacthub.io/operator: "false"
  artifacthub.io/prerelease: "true"
type: application
version: 2.0.0
appVersion: "2024.10.0"
