# SPDX-FileCopyrightText: Copyright (C) 2021-2026 Software Radio Systems Limited
# SPDX-License-Identifier: BSD-3-Clause-Open-MPI

apiVersion: v2
name: ru-emulator
description: OCUDU Radio Unit (O-RU) emulator for testing gNB deployments with OpenFronthaul interface
kubeVersion: ">= 1.24.0-0"
icon: https://gitlab.com/ocudu/ocudu_elements/ocudu_helm/-/raw/main/docs/logo.png
home: https://gitlab.com/ocudu/ocudu_elements/ocudu_helm
sources:
- https://gitlab.com/ocudu/ocudu_elements/ocudu_helm
- https://gitlab.com/ocudu/ocudu
keywords:
- ocudu
- ru
- oru
- radio-unit
- emulator
- openfronthaul
- 5g
- testing
- ran
annotations:
  artifacthub.io/category: openfronthaul
  artifacthub.io/license: BSD-3-Clause-Open-MPI
  artifacthub.io/operator: "false"
  artifacthub.io/prerelease: "true"
type: application
version: 2.4.1
appVersion: "2024.10.0"
