# SPDX-FileCopyrightText: Copyright (C) 2021-2026 Software Radio Systems Limited
# SPDX-License-Identifier: BSD-3-Clause-Open-MPI

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ocudu-du.fullname" . }}
  labels:
    {{- include "ocudu-du.labels" . | nindent 4 }}
    {{- with .Values.extraLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "ocudu-du.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ocudu-du.selectorLabels" . | nindent 8 }}
        {{- with .Values.extraLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "ocudu-du.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.network.hostNetwork }}
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      {{- end }}
      volumes:
        - name: entrypoint-volume-ocudu-du
          configMap:
            name: {{ include "ocudu-du.entrypointConfigmapName" . }}
            defaultMode: 0777
        - name: config-volume
          configMap:
            name: {{ include "ocudu-du.mainConfigmapName" . }}
        {{- if .Values.persistence.enabled }}
          {{- if eq .Values.persistence.type "pvc" }}
        - name: ocudu-logs
          persistentVolumeClaim:
            claimName: {{ include "ocudu-du.fullname" . }}-logs
          {{- else if eq .Values.persistence.type "hostPath" }}
        - name: ocudu-logs
          hostPath:
            path: {{ .Values.persistence.hostPath.path }}
            type: {{ .Values.persistence.hostPath.type }}
          {{- end }}
        {{- else }}
        - name: ocudu-logs
          emptyDir: {}
        {{- end }}
        {{- if or (and .Values.resources.limits (index .Values.resources.limits "hugepages-1Gi")) (and .Values.resources.requests (index .Values.resources.requests "hugepages-1Gi")) }}
        - name: hugepage-1gi
          emptyDir:
            medium: HugePages-1Gi
        {{- end }}
        {{- if or (and .Values.resources.limits (index .Values.resources.limits "hugepages-2Mi")) (and .Values.resources.requests (index .Values.resources.requests "hugepages-2Mi")) }}
        - name: hugepage-2mi
          emptyDir:
            medium: HugePages-2Mi
        {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          tty: true
          stdin: true
          securityContext:
            {{- if and .Values.metricsService.enabled .Values.metricsService.powercap.enabled }}
            {{- $ctx := deepCopy .Values.securityContext }}
            {{- $_ := set $ctx.capabilities "add" (append $ctx.capabilities.add "PERFMON") }}
            {{- toYaml $ctx | nindent 12 }}
            {{- else }}
            {{- toYaml .Values.securityContext | nindent 12 }}
            {{- end }}
          image: "{{ template "ocudu-du.image" .Values.image }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- $hasLimits := and .Values.resources .Values.resources.limits (gt (len .Values.resources.limits) 0) }}
          {{- $hasRequests := and .Values.resources .Values.resources.requests (gt (len .Values.resources.requests) 0) }}
          {{- if or $hasLimits $hasRequests .Values.sriovConfig.enabled }}
          resources:
            {{- if or $hasLimits .Values.sriovConfig.enabled }}
            limits:
              {{- if $hasLimits }}
              {{- toYaml .Values.resources.limits | nindent 14 }}
              {{- end }}
              {{- if .Values.sriovConfig.enabled }}
              {{ .Values.sriovConfig.extendedResourceName }}: 1
              {{- end }}
            {{- end }}
            {{- if or $hasRequests .Values.sriovConfig.enabled }}
            requests:
              {{- if $hasRequests }}
              {{- toYaml .Values.resources.requests | nindent 14 }}
              {{- end }}
              {{- if .Values.sriovConfig.enabled }}
              {{ .Values.sriovConfig.extendedResourceName }}: 1
              {{- end }}
            {{- end }}
          {{- end }}
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            exec:
              command: ["pgrep", "odu"]
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            exec:
              command: ["pgrep", "odu"]
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
          {{- end }}
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: HOSTNETWORK
              value: '{{ .Values.network.hostNetwork }}'
            - name: OCUDU_LOG_DIR
              value: {{ .Values.persistence.mountPath | quote }}
            - name: PRESERVE_OLD_LOGS
              value: {{ .Values.persistence.preserveOldLogs | quote }}
          {{- if and .Values.sriovConfig .Values.sriovConfig.enabled }}
            - name: RESOURCE_EXTENDED
              value: {{ .Values.sriovConfig.extendedResourceName | quote }}
          {{- end }}
          command: [ "/usr/bin/tini", "--" ]
          args: [ "/bin/bash", "-c", "/etc/entrypoint/entrypoint-ocudu-du.sh /etc/config/du-config.yml" ]
          volumeMounts:
            - name: entrypoint-volume-ocudu-du
              mountPath: /etc/entrypoint
            - name: config-volume
              mountPath: /etc/config/
            - name: ocudu-logs
              mountPath: {{ .Values.persistence.mountPath }}
            {{- if or (and .Values.resources.limits (index .Values.resources.limits "hugepages-1Gi")) (and .Values.resources.requests (index .Values.resources.requests "hugepages-1Gi")) }}
            - name: hugepage-1gi
              mountPath: /hugepages-1Gi
            {{- end }}
            {{- if or (and .Values.resources.limits (index .Values.resources.limits "hugepages-2Mi")) (and .Values.resources.requests (index .Values.resources.requests "hugepages-2Mi")) }}
            - name: hugepage-2mi
              mountPath: /hugepages-2Mi
            {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
