{{- if and (.Values.o1).enable_ocudu_o1 (.Values.o1).netconfServer.service }}

# SPDX-FileCopyrightText: Copyright (C) 2021-2026 Software Radio Systems Limited
# SPDX-License-Identifier: BSD-3-Clause-Open-MPI

apiVersion: v1
kind: Service
metadata:
  name: {{ include "ocudu-du.fullname" . }}-o1
  labels:
    {{- include "ocudu-du.labels" . | nindent 4 }}
    app.kubernetes.io/component: o1-netconf
spec:
  type: {{ (.Values.o1).netconfServer.service.type | default "NodePort" }}
  {{- if eq ((.Values.o1).netconfServer.service.type | default "NodePort") "LoadBalancer" }}
  {{- if (.Values.o1).netconfServer.service.loadBalancerIP }}
  loadBalancerIP: {{ (.Values.o1).netconfServer.service.loadBalancerIP }}
  {{- end }}
  {{- if (.Values.o1).netconfServer.service.loadBalancerClass }}
  loadBalancerClass: {{ (.Values.o1).netconfServer.service.loadBalancerClass }}
  {{- end }}
  {{- with (.Values.o1).netconfServer.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ . }}
  {{- end }}
  {{- end }}
  {{- with (.Values.o1).netconfServer.service.sessionAffinity }}
  sessionAffinity: {{ . }}
  {{- end }}
  selector:
    {{- include "ocudu-du.selectorLabels" . | nindent 4 }}
  ports:
    - name: o1
      port: {{ (.Values.o1).o1Port }}
      targetPort: {{ (.Values.o1).o1Port }}
      protocol: TCP
      {{- if and (eq ((.Values.o1).netconfServer.service.type | default "NodePort") "NodePort") ((.Values.o1).netconfServer.service.nodePort) }}
      nodePort: {{ (.Values.o1).netconfServer.service.nodePort }}
      {{- end }}
    {{- if (.Values.o1).netconfServer.tls.enabled }}
    - name: netconf-tls
      port: 6513
      targetPort: 6513
      protocol: TCP
      {{- if and (eq ((.Values.o1).netconfServer.service.type | default "NodePort") "NodePort") ((.Values.o1).netconfServer.tls.tlsNodePort) }}
      nodePort: {{ (.Values.o1).netconfServer.tls.tlsNodePort }}
      {{- end }}
    {{- end }}
{{- end }}
