{{- if .Values.service.enabled }}

# SPDX-FileCopyrightText: Copyright (C) 2021-2026 Software Radio Systems Limited
# SPDX-License-Identifier: BSD-3-Clause-Open-MPI

apiVersion: v1
kind: Service
metadata:
  name: {{ include "ocudu-du.fullname" . }}-lb
  labels:
    {{- include "ocudu-du.labels" . | nindent 4 }}
    app.kubernetes.io/component: f1
spec:
  type: {{ .Values.service.type | default "LoadBalancer" }}
  {{- if eq (.Values.service.type | default "LoadBalancer") "LoadBalancer" }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  {{- if .Values.service.loadBalancerClass }}
  loadBalancerClass: {{ .Values.service.loadBalancerClass }}
  {{- end }}
  {{- with .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ . }}
  {{- end }}
  {{- end }}
  {{- with .Values.service.sessionAffinity }}
  sessionAffinity: {{ . }}
  {{- end }}
  ports:
    {{- if .Values.service.ports.f1c.enabled }}
    - name: f1c
      port: {{ .Values.service.ports.f1c.port }}
      targetPort: {{ .Values.service.ports.f1c.targetPort | default .Values.service.ports.f1c.port }}
      protocol: {{ .Values.service.ports.f1c.protocol }}
      {{- if .Values.service.ports.f1c.nodePort }}
      nodePort: {{ .Values.service.ports.f1c.nodePort }}
      {{- end }}
    {{- end }}
    {{- if .Values.service.ports.f1u.enabled }}
    - name: f1u
      port: {{ .Values.service.ports.f1u.port }}
      targetPort: {{ .Values.service.ports.f1u.targetPort | default .Values.service.ports.f1u.port }}
      protocol: {{ .Values.service.ports.f1u.protocol }}
      {{- if .Values.service.ports.f1u.nodePort }}
      nodePort: {{ .Values.service.ports.f1u.nodePort }}
      {{- end }}
    {{- end }}
  selector:
    {{- include "ocudu-du.selectorLabels" . | nindent 4 }}
{{- end }}
