#
# Copyright 2021-2026 Software Radio Systems Limited
#
# By using this file, you agree to the terms and conditions set
# forth in the LICENSE file which can be found at the top level of
# the distribution.
#

apiVersion: v2
name: ocudu-gnb
description: OCUDU Project gNB (CU/DU Combined) Helm Chart
kubeVersion: ">= 1.24.0-0"
icon: https://gitlab.com/ocudu/ocudu_elements/ocudu_helm/-/raw/main/docs/logo.png
home: https://gitlab.com/ocudu/ocudu_elements/ocudu_helm
sources:
- https://gitlab.com/ocudu/ocudu_elements/ocudu_helm
- https://gitlab.com/ocudu/ocudu
keywords:
- ocudu
- 5g
- oran
- vran
- gnb
- ran
- mobile
- telecom
- networking
- cudu
annotations:
  artifacthub.io/category: networking
  artifacthub.io/license: BSD-3-Clause-Open-MPI
  artifacthub.io/operator: "false"
  artifacthub.io/prerelease: "false"
type: application
version: 3.3.0
appVersion: "25.04"
