# SPDX-FileCopyrightText: Copyright (C) 2021-2026 Software Radio Systems Limited
# SPDX-License-Identifier: BSD-3-Clause-Open-MPI

{{- if .Values.o1.enable_ocudu_o1 }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ocudu-gnb.o1ConfigmapName" . }}
data:
  {{- .Values.o1Config | toYaml | nindent 2 }}
{{- else }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ocudu-gnb.mainConfigmapName" . }}
data:
  {{- .Values.config | toYaml | nindent 2 }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ocudu-gnb.entrypointConfigmapName" . }}
data:
  entrypoint-srsgnb.sh: {{ tpl (.Files.Get "resources/entrypoint.sh") . | quote | default 000 }}
