{{- if and .Values.persistence.enabled (eq .Values.persistence.type "pvc") }}
#
# Copyright 2021-2026 Software Radio Systems Limited
#
# By using this file, you agree to the terms and conditions set
# forth in the LICENSE file which can be found at the top level of
# the distribution.
#

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ocudu-gnb.fullname" . }}-logs
  labels:
    {{- include "ocudu-gnb.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.pvc.accessMode }}
  {{- if .Values.persistence.pvc.storageClassName }}
  storageClassName: {{ .Values.persistence.pvc.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.pvc.size }}
{{- end }}
