{{- if and .Values.serviceAccount.create .Values.rbac.create }}
#
# Copyright 2021-2026 Software Radio Systems Limited
#
# By using this file, you agree to the terms and conditions set
# forth in the LICENSE file which can be found at the top level of
# the distribution.
#

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "ocudu-gnb.serviceAccountName" . }}
  labels:
    {{- include "ocudu-gnb.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "ocudu-gnb.serviceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "ocudu-gnb.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
