# SPDX-FileCopyrightText: Copyright (C) 2021-2026 Software Radio Systems Limited
# SPDX-License-Identifier: BSD-3-Clause-Open-MPI

apiVersion: net.gradiant.org/v1
kind: Open5GS
metadata:
  name: open5gs-sample
  namespace: default
spec:
  configuration:
    slices:
      - sst: "1"
        sd: "0x111111"
