# SPDX-FileCopyrightText: Copyright (C) 2021-2026 Software Radio Systems Limited
# SPDX-License-Identifier: BSD-3-Clause-Open-MPI

apiVersion: v2
name: tuned
description: Deploy tuned system optimization profiles on Kubernetes nodes for low-latency and real-time workloads
kubeVersion: ">= 1.24.0-0"
icon: https://avatars.githubusercontent.com/u/12718395
home: https://tuned-project.org/
sources:
- https://gitlab.com/ocudu/ocudu_elements/ocudu_helm
- https://github.com/redhat-performance/tuned
keywords:
- tuned
- performance
- optimization
- realtime
- low-latency
- sysctl
- system
- ocudu
annotations:
  artifacthub.io/category: system-optimization
  artifacthub.io/license: BSD-3-Clause-Open-MPI
  artifacthub.io/operator: "false"
  artifacthub.io/prerelease: "true"
type: application
version: 1.1.4
appVersion: "1.0.0"
